name: Neon CLI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-neon-cli:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Public IP
      run: |
        echo "Public IP: $(curl -s https://api.ipify.org)"
        
    - name: Curl Manually
      run: |
        GITHUB_TOKEN="${{ github.token }}"
        echo "First 3 chars of GITHUB_TOKEN: ${GITHUB_TOKEN:0:3}"
        curl -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/neondatabase/neonctl/releases/latest

      
    - name: Setup Neon
      uses: nhedger/setup-neon@v1
      with:
        version: "latest"
        token: ${{ github.token }}
        
    - name: Check Neon CLI version
      run: neonctl --version
